FROM golang:1.25-alpine AS builder

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

RUN apk add --no-cache git build-base

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata

RUN adduser -D -g '' appuser

COPY --from=builder /go/bin/goose /bin/goose

USER appuser
WORKDIR /migrations

ENTRYPOINT ["/bin/goose"]