// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"bernard/internal/domain/entity"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreateGroup provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateGroup(ctx context.Context, group entity.Group) (*entity.Group, error) {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) (*entity.Group, error)); ok {
		return returnFunc(ctx, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) *entity.Group); ok {
		r0 = returnFunc(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Group) error); ok {
		r1 = returnFunc(ctx, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockStorage_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - group entity.Group
func (_e *MockStorage_Expecter) CreateGroup(ctx interface{}, group interface{}) *MockStorage_CreateGroup_Call {
	return &MockStorage_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, group)}
}

func (_c *MockStorage_CreateGroup_Call) Run(run func(ctx context.Context, group entity.Group)) *MockStorage_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Group
		if args[1] != nil {
			arg1 = args[1].(entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreateGroup_Call) Return(group1 *entity.Group, err error) *MockStorage_CreateGroup_Call {
	_c.Call.Return(group1, err)
	return _c
}

func (_c *MockStorage_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, group entity.Group) (*entity.Group, error)) *MockStorage_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateProject(ctx context.Context, project entity.Project) (*entity.Project, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Project) (*entity.Project, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Project) *entity.Project); ok {
		r0 = returnFunc(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockStorage_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project entity.Project
func (_e *MockStorage_Expecter) CreateProject(ctx interface{}, project interface{}) *MockStorage_CreateProject_Call {
	return &MockStorage_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, project)}
}

func (_c *MockStorage_CreateProject_Call) Run(run func(ctx context.Context, project entity.Project)) *MockStorage_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Project
		if args[1] != nil {
			arg1 = args[1].(entity.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreateProject_Call) Return(project1 *entity.Project, err error) *MockStorage_CreateProject_Call {
	_c.Call.Return(project1, err)
	return _c
}

func (_c *MockStorage_CreateProject_Call) RunAndReturn(run func(ctx context.Context, project entity.Project) (*entity.Project, error)) *MockStorage_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateTask(ctx context.Context, task entity.Task) (*entity.Task, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Task) (*entity.Task, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Task) *entity.Task); ok {
		r0 = returnFunc(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockStorage_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task entity.Task
func (_e *MockStorage_Expecter) CreateTask(ctx interface{}, task interface{}) *MockStorage_CreateTask_Call {
	return &MockStorage_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockStorage_CreateTask_Call) Run(run func(ctx context.Context, task entity.Task)) *MockStorage_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Task
		if args[1] != nil {
			arg1 = args[1].(entity.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreateTask_Call) Return(task1 *entity.Task, err error) *MockStorage_CreateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockStorage_CreateTask_Call) RunAndReturn(run func(ctx context.Context, task entity.Task) (*entity.Task, error)) *MockStorage_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteGroup(ctx context.Context, groupID int64) (*entity.Group, error) {
	ret := _mock.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 *entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.Group, error)); ok {
		return returnFunc(ctx, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.Group); ok {
		r0 = returnFunc(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockStorage_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int64
func (_e *MockStorage_Expecter) DeleteGroup(ctx interface{}, groupID interface{}) *MockStorage_DeleteGroup_Call {
	return &MockStorage_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, groupID)}
}

func (_c *MockStorage_DeleteGroup_Call) Run(run func(ctx context.Context, groupID int64)) *MockStorage_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteGroup_Call) Return(group *entity.Group, err error) *MockStorage_DeleteGroup_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockStorage_DeleteGroup_Call) RunAndReturn(run func(ctx context.Context, groupID int64) (*entity.Group, error)) *MockStorage_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteProject(ctx context.Context, projectID int64) (*entity.Project, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 *entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.Project, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.Project); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockStorage_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
func (_e *MockStorage_Expecter) DeleteProject(ctx interface{}, projectID interface{}) *MockStorage_DeleteProject_Call {
	return &MockStorage_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, projectID)}
}

func (_c *MockStorage_DeleteProject_Call) Run(run func(ctx context.Context, projectID int64)) *MockStorage_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteProject_Call) Return(project *entity.Project, err error) *MockStorage_DeleteProject_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockStorage_DeleteProject_Call) RunAndReturn(run func(ctx context.Context, projectID int64) (*entity.Project, error)) *MockStorage_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteTask(ctx context.Context, userID uuid.UUID, id int64) (*entity.Task, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (*entity.Task, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) *entity.Task); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockStorage_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id int64
func (_e *MockStorage_Expecter) DeleteTask(ctx interface{}, userID interface{}, id interface{}) *MockStorage_DeleteTask_Call {
	return &MockStorage_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, userID, id)}
}

func (_c *MockStorage_DeleteTask_Call) Run(run func(ctx context.Context, userID uuid.UUID, id int64)) *MockStorage_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteTask_Call) Return(task *entity.Task, err error) *MockStorage_DeleteTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockStorage_DeleteTask_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id int64) (*entity.Task, error)) *MockStorage_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectTree provides a mock function for the type MockStorage
func (_mock *MockStorage) GetProjectTree(ctx context.Context, projectID int64, userID uuid.UUID) (*entity.Project, error) {
	ret := _mock.Called(ctx, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectTree")
	}

	var r0 *entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) (*entity.Project, error)); ok {
		return returnFunc(ctx, projectID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) *entity.Project); ok {
		r0 = returnFunc(ctx, projectID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetProjectTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectTree'
type MockStorage_GetProjectTree_Call struct {
	*mock.Call
}

// GetProjectTree is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) GetProjectTree(ctx interface{}, projectID interface{}, userID interface{}) *MockStorage_GetProjectTree_Call {
	return &MockStorage_GetProjectTree_Call{Call: _e.mock.On("GetProjectTree", ctx, projectID, userID)}
}

func (_c *MockStorage_GetProjectTree_Call) Run(run func(ctx context.Context, projectID int64, userID uuid.UUID)) *MockStorage_GetProjectTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_GetProjectTree_Call) Return(project *entity.Project, err error) *MockStorage_GetProjectTree_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockStorage_GetProjectTree_Call) RunAndReturn(run func(ctx context.Context, projectID int64, userID uuid.UUID) (*entity.Project, error)) *MockStorage_GetProjectTree_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjects provides a mock function for the type MockStorage
func (_mock *MockStorage) GetProjects(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.Project, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetProjects")
	}

	var r0 []*entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) ([]*entity.Project, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) []*entity.Project); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjects'
type MockStorage_GetProjects_Call struct {
	*mock.Call
}

// GetProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit uint64
//   - offset uint64
func (_e *MockStorage_Expecter) GetProjects(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockStorage_GetProjects_Call {
	return &MockStorage_GetProjects_Call{Call: _e.mock.On("GetProjects", ctx, userID, limit, offset)}
}

func (_c *MockStorage_GetProjects_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64)) *MockStorage_GetProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_GetProjects_Call) Return(projects []*entity.Project, err error) *MockStorage_GetProjects_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockStorage_GetProjects_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.Project, error)) *MockStorage_GetProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTask(ctx context.Context, id int64) (*entity.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockStorage_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) GetTask(ctx interface{}, id interface{}) *MockStorage_GetTask_Call {
	return &MockStorage_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockStorage_GetTask_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetTask_Call) Return(task *entity.Task, err error) *MockStorage_GetTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockStorage_GetTask_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.Task, error)) *MockStorage_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByDate provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTasksByDate(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByDate")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTasksByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByDate'
type MockStorage_GetTasksByDate_Call struct {
	*mock.Call
}

// GetTasksByDate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockStorage_Expecter) GetTasksByDate(ctx interface{}, userID interface{}, from interface{}, to interface{}) *MockStorage_GetTasksByDate_Call {
	return &MockStorage_GetTasksByDate_Call{Call: _e.mock.On("GetTasksByDate", ctx, userID, from, to)}
}

func (_c *MockStorage_GetTasksByDate_Call) Run(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time)) *MockStorage_GetTasksByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_GetTasksByDate_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_GetTasksByDate_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_GetTasksByDate_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time) ([]*entity.UserTasksTab, error)) *MockStorage_GetTasksByDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByPriority provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTasksByPriority(ctx context.Context, userID uuid.UUID, priority int) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID, priority)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByPriority")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID, priority)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, userID, priority)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTasksByPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByPriority'
type MockStorage_GetTasksByPriority_Call struct {
	*mock.Call
}

// GetTasksByPriority is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - priority int
func (_e *MockStorage_Expecter) GetTasksByPriority(ctx interface{}, userID interface{}, priority interface{}) *MockStorage_GetTasksByPriority_Call {
	return &MockStorage_GetTasksByPriority_Call{Call: _e.mock.On("GetTasksByPriority", ctx, userID, priority)}
}

func (_c *MockStorage_GetTasksByPriority_Call) Run(run func(ctx context.Context, userID uuid.UUID, priority int)) *MockStorage_GetTasksByPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_GetTasksByPriority_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_GetTasksByPriority_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_GetTasksByPriority_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, priority int) ([]*entity.UserTasksTab, error)) *MockStorage_GetTasksByPriority_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByTag provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTasksByTag(ctx context.Context, userID uuid.UUID, tag string) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByTag")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTasksByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByTag'
type MockStorage_GetTasksByTag_Call struct {
	*mock.Call
}

// GetTasksByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tag string
func (_e *MockStorage_Expecter) GetTasksByTag(ctx interface{}, userID interface{}, tag interface{}) *MockStorage_GetTasksByTag_Call {
	return &MockStorage_GetTasksByTag_Call{Call: _e.mock.On("GetTasksByTag", ctx, userID, tag)}
}

func (_c *MockStorage_GetTasksByTag_Call) Run(run func(ctx context.Context, userID uuid.UUID, tag string)) *MockStorage_GetTasksByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_GetTasksByTag_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_GetTasksByTag_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_GetTasksByTag_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tag string) ([]*entity.UserTasksTab, error)) *MockStorage_GetTasksByTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockStorage
func (_mock *MockStorage) ListTasks(ctx context.Context, userID uuid.UUID) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockStorage_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) ListTasks(ctx interface{}, userID interface{}) *MockStorage_ListTasks_Call {
	return &MockStorage_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, userID)}
}

func (_c *MockStorage_ListTasks_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStorage_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_ListTasks_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_ListTasks_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_ListTasks_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.UserTasksTab, error)) *MockStorage_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateGroup(ctx context.Context, group entity.Group) (*entity.Group, error) {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 *entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) (*entity.Group, error)); ok {
		return returnFunc(ctx, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) *entity.Group); ok {
		r0 = returnFunc(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Group) error); ok {
		r1 = returnFunc(ctx, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockStorage_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - group entity.Group
func (_e *MockStorage_Expecter) UpdateGroup(ctx interface{}, group interface{}) *MockStorage_UpdateGroup_Call {
	return &MockStorage_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, group)}
}

func (_c *MockStorage_UpdateGroup_Call) Run(run func(ctx context.Context, group entity.Group)) *MockStorage_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Group
		if args[1] != nil {
			arg1 = args[1].(entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateGroup_Call) Return(group1 *entity.Group, err error) *MockStorage_UpdateGroup_Call {
	_c.Call.Return(group1, err)
	return _c
}

func (_c *MockStorage_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, group entity.Group) (*entity.Group, error)) *MockStorage_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateProject(ctx context.Context, project entity.Project) (*entity.Project, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Project) (*entity.Project, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Project) *entity.Project); ok {
		r0 = returnFunc(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockStorage_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project entity.Project
func (_e *MockStorage_Expecter) UpdateProject(ctx interface{}, project interface{}) *MockStorage_UpdateProject_Call {
	return &MockStorage_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, project)}
}

func (_c *MockStorage_UpdateProject_Call) Run(run func(ctx context.Context, project entity.Project)) *MockStorage_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Project
		if args[1] != nil {
			arg1 = args[1].(entity.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateProject_Call) Return(project1 *entity.Project, err error) *MockStorage_UpdateProject_Call {
	_c.Call.Return(project1, err)
	return _c
}

func (_c *MockStorage_UpdateProject_Call) RunAndReturn(run func(ctx context.Context, project entity.Project) (*entity.Project, error)) *MockStorage_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateTask(ctx context.Context, task entity.Task) (*entity.Task, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Task) (*entity.Task, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Task) *entity.Task); ok {
		r0 = returnFunc(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockStorage_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task entity.Task
func (_e *MockStorage_Expecter) UpdateTask(ctx interface{}, task interface{}) *MockStorage_UpdateTask_Call {
	return &MockStorage_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, task)}
}

func (_c *MockStorage_UpdateTask_Call) Run(run func(ctx context.Context, task entity.Task)) *MockStorage_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Task
		if args[1] != nil {
			arg1 = args[1].(entity.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateTask_Call) Return(task1 *entity.Task, err error) *MockStorage_UpdateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockStorage_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, task entity.Task) (*entity.Task, error)) *MockStorage_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
