// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"bernard/internal/domain/entity"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// AddTagToTask provides a mock function for the type MockStorage
func (_mock *MockStorage) AddTagToTask(ctx context.Context, tagID int64, taskID int64, userID uuid.UUID) error {
	ret := _mock.Called(ctx, tagID, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tagID, taskID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_AddTagToTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagToTask'
type MockStorage_AddTagToTask_Call struct {
	*mock.Call
}

// AddTagToTask is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int64
//   - taskID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) AddTagToTask(ctx interface{}, tagID interface{}, taskID interface{}, userID interface{}) *MockStorage_AddTagToTask_Call {
	return &MockStorage_AddTagToTask_Call{Call: _e.mock.On("AddTagToTask", ctx, tagID, taskID, userID)}
}

func (_c *MockStorage_AddTagToTask_Call) Run(run func(ctx context.Context, tagID int64, taskID int64, userID uuid.UUID)) *MockStorage_AddTagToTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_AddTagToTask_Call) Return(err error) *MockStorage_AddTagToTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_AddTagToTask_Call) RunAndReturn(run func(ctx context.Context, tagID int64, taskID int64, userID uuid.UUID) error) *MockStorage_AddTagToTask_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveOldTasks provides a mock function for the type MockStorage
func (_mock *MockStorage) ArchiveOldTasks(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveOldTasks")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_ArchiveOldTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveOldTasks'
type MockStorage_ArchiveOldTasks_Call struct {
	*mock.Call
}

// ArchiveOldTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) ArchiveOldTasks(ctx interface{}) *MockStorage_ArchiveOldTasks_Call {
	return &MockStorage_ArchiveOldTasks_Call{Call: _e.mock.On("ArchiveOldTasks", ctx)}
}

func (_c *MockStorage_ArchiveOldTasks_Call) Run(run func(ctx context.Context)) *MockStorage_ArchiveOldTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_ArchiveOldTasks_Call) Return(n int64, err error) *MockStorage_ArchiveOldTasks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_ArchiveOldTasks_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockStorage_ArchiveOldTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ArchiveTask provides a mock function for the type MockStorage
func (_mock *MockStorage) ArchiveTask(ctx context.Context, userID uuid.UUID, taskID int64) (*entity.Task, error) {
	ret := _mock.Called(ctx, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (*entity.Task, error)); ok {
		return returnFunc(ctx, userID, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) *entity.Task); ok {
		r0 = returnFunc(ctx, userID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = returnFunc(ctx, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_ArchiveTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveTask'
type MockStorage_ArchiveTask_Call struct {
	*mock.Call
}

// ArchiveTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - taskID int64
func (_e *MockStorage_Expecter) ArchiveTask(ctx interface{}, userID interface{}, taskID interface{}) *MockStorage_ArchiveTask_Call {
	return &MockStorage_ArchiveTask_Call{Call: _e.mock.On("ArchiveTask", ctx, userID, taskID)}
}

func (_c *MockStorage_ArchiveTask_Call) Run(run func(ctx context.Context, userID uuid.UUID, taskID int64)) *MockStorage_ArchiveTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_ArchiveTask_Call) Return(task *entity.Task, err error) *MockStorage_ArchiveTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockStorage_ArchiveTask_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, taskID int64) (*entity.Task, error)) *MockStorage_ArchiveTask_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateGroup(ctx context.Context, group entity.Group) (*entity.Group, error) {
	ret := _mock.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) (*entity.Group, error)); ok {
		return returnFunc(ctx, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Group) *entity.Group); ok {
		r0 = returnFunc(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Group) error); ok {
		r1 = returnFunc(ctx, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockStorage_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - group entity.Group
func (_e *MockStorage_Expecter) CreateGroup(ctx interface{}, group interface{}) *MockStorage_CreateGroup_Call {
	return &MockStorage_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, group)}
}

func (_c *MockStorage_CreateGroup_Call) Run(run func(ctx context.Context, group entity.Group)) *MockStorage_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Group
		if args[1] != nil {
			arg1 = args[1].(entity.Group)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreateGroup_Call) Return(group1 *entity.Group, err error) *MockStorage_CreateGroup_Call {
	_c.Call.Return(group1, err)
	return _c
}

func (_c *MockStorage_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, group entity.Group) (*entity.Group, error)) *MockStorage_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateProject(ctx context.Context, project entity.Project) (*entity.Project, error) {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Project) (*entity.Project, error)); ok {
		return returnFunc(ctx, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Project) *entity.Project); ok {
		r0 = returnFunc(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Project) error); ok {
		r1 = returnFunc(ctx, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockStorage_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project entity.Project
func (_e *MockStorage_Expecter) CreateProject(ctx interface{}, project interface{}) *MockStorage_CreateProject_Call {
	return &MockStorage_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, project)}
}

func (_c *MockStorage_CreateProject_Call) Run(run func(ctx context.Context, project entity.Project)) *MockStorage_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Project
		if args[1] != nil {
			arg1 = args[1].(entity.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreateProject_Call) Return(project1 *entity.Project, err error) *MockStorage_CreateProject_Call {
	_c.Call.Return(project1, err)
	return _c
}

func (_c *MockStorage_CreateProject_Call) RunAndReturn(run func(ctx context.Context, project entity.Project) (*entity.Project, error)) *MockStorage_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTag provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateTag(ctx context.Context, tag entity.Tag) (*entity.Tag, error) {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 *entity.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Tag) (*entity.Tag, error)); ok {
		return returnFunc(ctx, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Tag) *entity.Tag); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Tag) error); ok {
		r1 = returnFunc(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockStorage_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag entity.Tag
func (_e *MockStorage_Expecter) CreateTag(ctx interface{}, tag interface{}) *MockStorage_CreateTag_Call {
	return &MockStorage_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, tag)}
}

func (_c *MockStorage_CreateTag_Call) Run(run func(ctx context.Context, tag entity.Tag)) *MockStorage_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Tag
		if args[1] != nil {
			arg1 = args[1].(entity.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreateTag_Call) Return(tag1 *entity.Tag, err error) *MockStorage_CreateTag_Call {
	_c.Call.Return(tag1, err)
	return _c
}

func (_c *MockStorage_CreateTag_Call) RunAndReturn(run func(ctx context.Context, tag entity.Tag) (*entity.Tag, error)) *MockStorage_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateTask(ctx context.Context, task entity.Task, tasksIDs []int64) (*entity.Task, error) {
	ret := _mock.Called(ctx, task, tasksIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Task, []int64) (*entity.Task, error)); ok {
		return returnFunc(ctx, task, tasksIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.Task, []int64) *entity.Task); ok {
		r0 = returnFunc(ctx, task, tasksIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.Task, []int64) error); ok {
		r1 = returnFunc(ctx, task, tasksIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockStorage_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task entity.Task
//   - tasksIDs []int64
func (_e *MockStorage_Expecter) CreateTask(ctx interface{}, task interface{}, tasksIDs interface{}) *MockStorage_CreateTask_Call {
	return &MockStorage_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task, tasksIDs)}
}

func (_c *MockStorage_CreateTask_Call) Run(run func(ctx context.Context, task entity.Task, tasksIDs []int64)) *MockStorage_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.Task
		if args[1] != nil {
			arg1 = args[1].(entity.Task)
		}
		var arg2 []int64
		if args[2] != nil {
			arg2 = args[2].([]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_CreateTask_Call) Return(task1 *entity.Task, err error) *MockStorage_CreateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockStorage_CreateTask_Call) RunAndReturn(run func(ctx context.Context, task entity.Task, tasksIDs []int64) (*entity.Task, error)) *MockStorage_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteGroup(ctx context.Context, groupID int64, userID uuid.UUID) error {
	ret := _mock.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockStorage_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) DeleteGroup(ctx interface{}, groupID interface{}, userID interface{}) *MockStorage_DeleteGroup_Call {
	return &MockStorage_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, groupID, userID)}
}

func (_c *MockStorage_DeleteGroup_Call) Run(run func(ctx context.Context, groupID int64, userID uuid.UUID)) *MockStorage_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteGroup_Call) Return(err error) *MockStorage_DeleteGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteGroup_Call) RunAndReturn(run func(ctx context.Context, groupID int64, userID uuid.UUID) error) *MockStorage_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteProject(ctx context.Context, projectID int64, userID uuid.UUID) error {
	ret := _mock.Called(ctx, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, projectID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockStorage_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) DeleteProject(ctx interface{}, projectID interface{}, userID interface{}) *MockStorage_DeleteProject_Call {
	return &MockStorage_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, projectID, userID)}
}

func (_c *MockStorage_DeleteProject_Call) Run(run func(ctx context.Context, projectID int64, userID uuid.UUID)) *MockStorage_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteProject_Call) Return(err error) *MockStorage_DeleteProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteProject_Call) RunAndReturn(run func(ctx context.Context, projectID int64, userID uuid.UUID) error) *MockStorage_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteTag(ctx context.Context, tagID int64, userID uuid.UUID) error {
	ret := _mock.Called(ctx, tagID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tagID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockStorage_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) DeleteTag(ctx interface{}, tagID interface{}, userID interface{}) *MockStorage_DeleteTag_Call {
	return &MockStorage_DeleteTag_Call{Call: _e.mock.On("DeleteTag", ctx, tagID, userID)}
}

func (_c *MockStorage_DeleteTag_Call) Run(run func(ctx context.Context, tagID int64, userID uuid.UUID)) *MockStorage_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteTag_Call) Return(err error) *MockStorage_DeleteTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteTag_Call) RunAndReturn(run func(ctx context.Context, tagID int64, userID uuid.UUID) error) *MockStorage_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockStorage
func (_mock *MockStorage) DeleteTask(ctx context.Context, userID uuid.UUID, id int64) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockStorage_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id int64
func (_e *MockStorage_Expecter) DeleteTask(ctx interface{}, userID interface{}, id interface{}) *MockStorage_DeleteTask_Call {
	return &MockStorage_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, userID, id)}
}

func (_c *MockStorage_DeleteTask_Call) Run(run func(ctx context.Context, userID uuid.UUID, id int64)) *MockStorage_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_DeleteTask_Call) Return(err error) *MockStorage_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_DeleteTask_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id int64) error) *MockStorage_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectTree provides a mock function for the type MockStorage
func (_mock *MockStorage) GetProjectTree(ctx context.Context, projectID int64, userID uuid.UUID) (*entity.Project, error) {
	ret := _mock.Called(ctx, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectTree")
	}

	var r0 *entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) (*entity.Project, error)); ok {
		return returnFunc(ctx, projectID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) *entity.Project); ok {
		r0 = returnFunc(ctx, projectID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetProjectTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectTree'
type MockStorage_GetProjectTree_Call struct {
	*mock.Call
}

// GetProjectTree is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) GetProjectTree(ctx interface{}, projectID interface{}, userID interface{}) *MockStorage_GetProjectTree_Call {
	return &MockStorage_GetProjectTree_Call{Call: _e.mock.On("GetProjectTree", ctx, projectID, userID)}
}

func (_c *MockStorage_GetProjectTree_Call) Run(run func(ctx context.Context, projectID int64, userID uuid.UUID)) *MockStorage_GetProjectTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_GetProjectTree_Call) Return(project *entity.Project, err error) *MockStorage_GetProjectTree_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockStorage_GetProjectTree_Call) RunAndReturn(run func(ctx context.Context, projectID int64, userID uuid.UUID) (*entity.Project, error)) *MockStorage_GetProjectTree_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjects provides a mock function for the type MockStorage
func (_mock *MockStorage) GetProjects(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.Project, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetProjects")
	}

	var r0 []*entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) ([]*entity.Project, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) []*entity.Project); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjects'
type MockStorage_GetProjects_Call struct {
	*mock.Call
}

// GetProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit uint64
//   - offset uint64
func (_e *MockStorage_Expecter) GetProjects(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockStorage_GetProjects_Call {
	return &MockStorage_GetProjects_Call{Call: _e.mock.On("GetProjects", ctx, userID, limit, offset)}
}

func (_c *MockStorage_GetProjects_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64)) *MockStorage_GetProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_GetProjects_Call) Return(projects []*entity.Project, err error) *MockStorage_GetProjects_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockStorage_GetProjects_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.Project, error)) *MockStorage_GetProjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTag(ctx context.Context, tagID int64, userID uuid.UUID) (*entity.Tag, error) {
	ret := _mock.Called(ctx, tagID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 *entity.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) (*entity.Tag, error)); ok {
		return returnFunc(ctx, tagID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) *entity.Tag); ok {
		r0 = returnFunc(ctx, tagID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tagID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type MockStorage_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) GetTag(ctx interface{}, tagID interface{}, userID interface{}) *MockStorage_GetTag_Call {
	return &MockStorage_GetTag_Call{Call: _e.mock.On("GetTag", ctx, tagID, userID)}
}

func (_c *MockStorage_GetTag_Call) Run(run func(ctx context.Context, tagID int64, userID uuid.UUID)) *MockStorage_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_GetTag_Call) Return(tag *entity.Tag, err error) *MockStorage_GetTag_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockStorage_GetTag_Call) RunAndReturn(run func(ctx context.Context, tagID int64, userID uuid.UUID) (*entity.Tag, error)) *MockStorage_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagList provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTagList(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.Tag, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTagList")
	}

	var r0 []*entity.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) ([]*entity.Tag, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) []*entity.Tag); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTagList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagList'
type MockStorage_GetTagList_Call struct {
	*mock.Call
}

// GetTagList is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit uint64
//   - offset uint64
func (_e *MockStorage_Expecter) GetTagList(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockStorage_GetTagList_Call {
	return &MockStorage_GetTagList_Call{Call: _e.mock.On("GetTagList", ctx, userID, limit, offset)}
}

func (_c *MockStorage_GetTagList_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64)) *MockStorage_GetTagList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_GetTagList_Call) Return(tags []*entity.Tag, err error) *MockStorage_GetTagList_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockStorage_GetTagList_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.Tag, error)) *MockStorage_GetTagList_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTask(ctx context.Context, id int64, userID uuid.UUID) (*entity.Task, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) (*entity.Task, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) *entity.Task); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockStorage_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) GetTask(ctx interface{}, id interface{}, userID interface{}) *MockStorage_GetTask_Call {
	return &MockStorage_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id, userID)}
}

func (_c *MockStorage_GetTask_Call) Run(run func(ctx context.Context, id int64, userID uuid.UUID)) *MockStorage_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_GetTask_Call) Return(task *entity.Task, err error) *MockStorage_GetTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockStorage_GetTask_Call) RunAndReturn(run func(ctx context.Context, id int64, userID uuid.UUID) (*entity.Task, error)) *MockStorage_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByDate provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTasksByDate(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time, limit uint64, offset uint64) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID, from, to, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByDate")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, uint64, uint64) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID, from, to, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time, uint64, uint64) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID, from, to, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, from, to, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTasksByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByDate'
type MockStorage_GetTasksByDate_Call struct {
	*mock.Call
}

// GetTasksByDate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - from time.Time
//   - to time.Time
//   - limit uint64
//   - offset uint64
func (_e *MockStorage_Expecter) GetTasksByDate(ctx interface{}, userID interface{}, from interface{}, to interface{}, limit interface{}, offset interface{}) *MockStorage_GetTasksByDate_Call {
	return &MockStorage_GetTasksByDate_Call{Call: _e.mock.On("GetTasksByDate", ctx, userID, from, to, limit, offset)}
}

func (_c *MockStorage_GetTasksByDate_Call) Run(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time, limit uint64, offset uint64)) *MockStorage_GetTasksByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		var arg5 uint64
		if args[5] != nil {
			arg5 = args[5].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockStorage_GetTasksByDate_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_GetTasksByDate_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_GetTasksByDate_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, from time.Time, to time.Time, limit uint64, offset uint64) ([]*entity.UserTasksTab, error)) *MockStorage_GetTasksByDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByPriority provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTasksByPriority(ctx context.Context, userID uuid.UUID, priority int, limit uint64, offset uint64) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID, priority, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByPriority")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uint64, uint64) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID, priority, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uint64, uint64) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID, priority, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, priority, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTasksByPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByPriority'
type MockStorage_GetTasksByPriority_Call struct {
	*mock.Call
}

// GetTasksByPriority is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - priority int
//   - limit uint64
//   - offset uint64
func (_e *MockStorage_Expecter) GetTasksByPriority(ctx interface{}, userID interface{}, priority interface{}, limit interface{}, offset interface{}) *MockStorage_GetTasksByPriority_Call {
	return &MockStorage_GetTasksByPriority_Call{Call: _e.mock.On("GetTasksByPriority", ctx, userID, priority, limit, offset)}
}

func (_c *MockStorage_GetTasksByPriority_Call) Run(run func(ctx context.Context, userID uuid.UUID, priority int, limit uint64, offset uint64)) *MockStorage_GetTasksByPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorage_GetTasksByPriority_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_GetTasksByPriority_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_GetTasksByPriority_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, priority int, limit uint64, offset uint64) ([]*entity.UserTasksTab, error)) *MockStorage_GetTasksByPriority_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByTag provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTasksByTag(ctx context.Context, userID uuid.UUID, tagID int64, limit uint64, offset uint64) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID, tagID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByTag")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, uint64, uint64) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID, tagID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, uint64, uint64) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID, tagID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, tagID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTasksByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByTag'
type MockStorage_GetTasksByTag_Call struct {
	*mock.Call
}

// GetTasksByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tagID int64
//   - limit uint64
//   - offset uint64
func (_e *MockStorage_Expecter) GetTasksByTag(ctx interface{}, userID interface{}, tagID interface{}, limit interface{}, offset interface{}) *MockStorage_GetTasksByTag_Call {
	return &MockStorage_GetTasksByTag_Call{Call: _e.mock.On("GetTasksByTag", ctx, userID, tagID, limit, offset)}
}

func (_c *MockStorage_GetTasksByTag_Call) Run(run func(ctx context.Context, userID uuid.UUID, tagID int64, limit uint64, offset uint64)) *MockStorage_GetTasksByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorage_GetTasksByTag_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_GetTasksByTag_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_GetTasksByTag_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tagID int64, limit uint64, offset uint64) ([]*entity.UserTasksTab, error)) *MockStorage_GetTasksByTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockStorage
func (_mock *MockStorage) ListTasks(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.UserTasksTab, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*entity.UserTasksTab
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) ([]*entity.UserTasksTab, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uint64, uint64) []*entity.UserTasksTab); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserTasksTab)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockStorage_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit uint64
//   - offset uint64
func (_e *MockStorage_Expecter) ListTasks(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockStorage_ListTasks_Call {
	return &MockStorage_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, userID, limit, offset)}
}

func (_c *MockStorage_ListTasks_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64)) *MockStorage_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_ListTasks_Call) Return(userTasksTabs []*entity.UserTasksTab, err error) *MockStorage_ListTasks_Call {
	_c.Call.Return(userTasksTabs, err)
	return _c
}

func (_c *MockStorage_ListTasks_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit uint64, offset uint64) ([]*entity.UserTasksTab, error)) *MockStorage_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTagFromTask provides a mock function for the type MockStorage
func (_mock *MockStorage) RemoveTagFromTask(ctx context.Context, tagID int64, taskID int64, userID uuid.UUID) error {
	ret := _mock.Called(ctx, tagID, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTagFromTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tagID, taskID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_RemoveTagFromTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTagFromTask'
type MockStorage_RemoveTagFromTask_Call struct {
	*mock.Call
}

// RemoveTagFromTask is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int64
//   - taskID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) RemoveTagFromTask(ctx interface{}, tagID interface{}, taskID interface{}, userID interface{}) *MockStorage_RemoveTagFromTask_Call {
	return &MockStorage_RemoveTagFromTask_Call{Call: _e.mock.On("RemoveTagFromTask", ctx, tagID, taskID, userID)}
}

func (_c *MockStorage_RemoveTagFromTask_Call) Run(run func(ctx context.Context, tagID int64, taskID int64, userID uuid.UUID)) *MockStorage_RemoveTagFromTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_RemoveTagFromTask_Call) Return(err error) *MockStorage_RemoveTagFromTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_RemoveTagFromTask_Call) RunAndReturn(run func(ctx context.Context, tagID int64, taskID int64, userID uuid.UUID) error) *MockStorage_RemoveTagFromTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateGroup(ctx context.Context, group entity.UpdateGroupRequest, userID uuid.UUID, groupID int64) (*entity.Group, error) {
	ret := _mock.Called(ctx, group, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 *entity.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UpdateGroupRequest, uuid.UUID, int64) (*entity.Group, error)); ok {
		return returnFunc(ctx, group, userID, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UpdateGroupRequest, uuid.UUID, int64) *entity.Group); ok {
		r0 = returnFunc(ctx, group, userID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.UpdateGroupRequest, uuid.UUID, int64) error); ok {
		r1 = returnFunc(ctx, group, userID, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockStorage_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - group entity.UpdateGroupRequest
//   - userID uuid.UUID
//   - groupID int64
func (_e *MockStorage_Expecter) UpdateGroup(ctx interface{}, group interface{}, userID interface{}, groupID interface{}) *MockStorage_UpdateGroup_Call {
	return &MockStorage_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, group, userID, groupID)}
}

func (_c *MockStorage_UpdateGroup_Call) Run(run func(ctx context.Context, group entity.UpdateGroupRequest, userID uuid.UUID, groupID int64)) *MockStorage_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.UpdateGroupRequest
		if args[1] != nil {
			arg1 = args[1].(entity.UpdateGroupRequest)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateGroup_Call) Return(group1 *entity.Group, err error) *MockStorage_UpdateGroup_Call {
	_c.Call.Return(group1, err)
	return _c
}

func (_c *MockStorage_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, group entity.UpdateGroupRequest, userID uuid.UUID, groupID int64) (*entity.Group, error)) *MockStorage_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateProject(ctx context.Context, project entity.UpdateProjectRequest, projectID int64, userID uuid.UUID) (*entity.Project, error) {
	ret := _mock.Called(ctx, project, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *entity.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UpdateProjectRequest, int64, uuid.UUID) (*entity.Project, error)); ok {
		return returnFunc(ctx, project, projectID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UpdateProjectRequest, int64, uuid.UUID) *entity.Project); ok {
		r0 = returnFunc(ctx, project, projectID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.UpdateProjectRequest, int64, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, project, projectID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockStorage_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project entity.UpdateProjectRequest
//   - projectID int64
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) UpdateProject(ctx interface{}, project interface{}, projectID interface{}, userID interface{}) *MockStorage_UpdateProject_Call {
	return &MockStorage_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, project, projectID, userID)}
}

func (_c *MockStorage_UpdateProject_Call) Run(run func(ctx context.Context, project entity.UpdateProjectRequest, projectID int64, userID uuid.UUID)) *MockStorage_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.UpdateProjectRequest
		if args[1] != nil {
			arg1 = args[1].(entity.UpdateProjectRequest)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateProject_Call) Return(project1 *entity.Project, err error) *MockStorage_UpdateProject_Call {
	_c.Call.Return(project1, err)
	return _c
}

func (_c *MockStorage_UpdateProject_Call) RunAndReturn(run func(ctx context.Context, project entity.UpdateProjectRequest, projectID int64, userID uuid.UUID) (*entity.Project, error)) *MockStorage_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTag provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateTag(ctx context.Context, tagID int64, name *string, color *string, userID uuid.UUID) (*entity.Tag, error) {
	ret := _mock.Called(ctx, tagID, name, color, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTag")
	}

	var r0 *entity.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *string, *string, uuid.UUID) (*entity.Tag, error)); ok {
		return returnFunc(ctx, tagID, name, color, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *string, *string, uuid.UUID) *entity.Tag); ok {
		r0 = returnFunc(ctx, tagID, name, color, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *string, *string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tagID, name, color, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UpdateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTag'
type MockStorage_UpdateTag_Call struct {
	*mock.Call
}

// UpdateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int64
//   - name *string
//   - color *string
//   - userID uuid.UUID
func (_e *MockStorage_Expecter) UpdateTag(ctx interface{}, tagID interface{}, name interface{}, color interface{}, userID interface{}) *MockStorage_UpdateTag_Call {
	return &MockStorage_UpdateTag_Call{Call: _e.mock.On("UpdateTag", ctx, tagID, name, color, userID)}
}

func (_c *MockStorage_UpdateTag_Call) Run(run func(ctx context.Context, tagID int64, name *string, color *string, userID uuid.UUID)) *MockStorage_UpdateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateTag_Call) Return(tag *entity.Tag, err error) *MockStorage_UpdateTag_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockStorage_UpdateTag_Call) RunAndReturn(run func(ctx context.Context, tagID int64, name *string, color *string, userID uuid.UUID) (*entity.Tag, error)) *MockStorage_UpdateTag_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateTask(ctx context.Context, task entity.UpdateTaskRequest, userID uuid.UUID, taskID int64) (*entity.Task, error) {
	ret := _mock.Called(ctx, task, userID, taskID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UpdateTaskRequest, uuid.UUID, int64) (*entity.Task, error)); ok {
		return returnFunc(ctx, task, userID, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UpdateTaskRequest, uuid.UUID, int64) *entity.Task); ok {
		r0 = returnFunc(ctx, task, userID, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.UpdateTaskRequest, uuid.UUID, int64) error); ok {
		r1 = returnFunc(ctx, task, userID, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockStorage_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task entity.UpdateTaskRequest
//   - userID uuid.UUID
//   - taskID int64
func (_e *MockStorage_Expecter) UpdateTask(ctx interface{}, task interface{}, userID interface{}, taskID interface{}) *MockStorage_UpdateTask_Call {
	return &MockStorage_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, task, userID, taskID)}
}

func (_c *MockStorage_UpdateTask_Call) Run(run func(ctx context.Context, task entity.UpdateTaskRequest, userID uuid.UUID, taskID int64)) *MockStorage_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.UpdateTaskRequest
		if args[1] != nil {
			arg1 = args[1].(entity.UpdateTaskRequest)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateTask_Call) Return(task1 *entity.Task, err error) *MockStorage_UpdateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockStorage_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, task entity.UpdateTaskRequest, userID uuid.UUID, taskID int64) (*entity.Task, error)) *MockStorage_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
